# Generated by Django 3.2.7 on 2021-10-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='usernamme',
            new_name='username',
        ),
    ]
