# Generated by Django 3.2.7 on 2021-10-12 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_privatechatroom_privatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechatroom',
            name='administrators',
            field=models.ManyToManyField(related_name='private_admin_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatechatroom',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owning_chats', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='privatechatroom',
            name='room_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
