# Generated by Django 3.2.7 on 2021-10-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20211012_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechatroom',
            name='room_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
