# Generated by Django 3.2.7 on 2021-10-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_privatechatroom_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechatroom',
            name='connected_users',
            field=models.IntegerField(default=0),
        ),
    ]
