# Generated by Django 3.2.7 on 2021-10-31 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_privatechatroom_connected_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechatroom',
            name='connected_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
