version: "3.8"

services:

  # Postgres database
  db:
    image: postgres
    restart: always
    volumes: 
      - ./storage/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: postgres_db
    ports:
      - "5432:5432"

  # redis
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./storage/redis/data:/data
      
  # Django Application
  app:
    build: .
    volumes:
      - .:/django
      - ./storage/static:/vol/static
    ports:
      - "8000:8000"
    image: app:django
    container_name: django_app
    restart: always
    depends_on:
      - db
      - redis

  # Nginx Proxy
  proxy:
    build:
      context: ./nginx
    restart: always
    volumes:
      - ./storage/static:/vol/static
    ports:
      - "80:80"
    depends_on:
      - app
