# Generated by Django 3.2.7 on 2021-10-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='message',
            new_name='content',
        ),
    ]
